# Generated by Django 3.0.3 on 2020-05-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reviewrestaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrestaurant',
            name='recipe',
        ),
        migrations.AddField(
            model_name='reviewrestaurant',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
        migrations.RemoveField(
            model_name='reviewrestaurant',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='reviewrestaurant',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant'),
        ),
    ]
