# Generated by Django 3.0.3 on 2020-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200526_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrestaurant',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
