# Generated by Django 3.0.3 on 2020-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
