# Generated by Django 3.0.3 on 2020-06-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField(blank=True)),
                ('method_type', models.CharField(blank=True, max_length=50)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('response_code', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
