# Generated by Django 3.0.3 on 2020-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(blank=True, max_length=255)),
                ('config_value', models.CharField(blank=True, max_length=255)),
                ('config_description', models.CharField(default='no description provided', max_length=255)),
            ],
        ),
    ]
